# -*- coding: utf-8 -*-
"""HybridPasswordCracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKLvsmppyiwq5ROboSnBjaduGs1mFeUq
"""

import hashlib
import itertools

def hybrid_attack(target_hash, dictionary, characters, max_suffix_length):
    with open(dictionary, 'r') as f:
        for word in f:
            word = word.strip()
            word_hash = hashlib.md5(word.encode()).hexdigest()
            if word_hash == target_hash:
                return word
            for length in range(1, max_suffix_length + 1):
                for suffix in itertools.product(characters, repeat=length):
                    guess = word + ''.join(suffix)
                    guess_hash = hashlib.md5(guess.encode()).hexdigest()
                    if guess_hash == target_hash:
                        return guess
    return None

key = "password123"
target_hash = hashlib.md5(key.encode()).hexdigest()
dictionary = 'common_passwords.txt'
characters = '1234567890@$#'
max_suffix_length = 4
password = hybrid_attack(target_hash, dictionary, characters, max_suffix_length)
if password:
    print(f"Password found: {password}")
else:
    print("Password not found")

